import React from "react";
import { TrendingUp, Users, DollarSign } from "lucide-react";
import { Button } from "./ui/button";

const Hero = () => {
  const scrollToPricing = () => {
    const element = document.getElementById("pricing");
    if (element) {
      element.scrollIntoView({ behavior: "smooth" });
    }
  };

  return (
    <section className="pt-24 pb-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-6xl mx-auto">
        <div className="text-center">
          <div className="inline-flex items-center px-4 py-2 bg-slate-100 rounded-full text-sm text-slate-600 mb-8 animate-fade-in">
            <TrendingUp size={16} className="mr-2" />
            Proven System for Online Success
          </div>
          
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-slate-900 mb-6 leading-tight animate-slide-up">
            How to Earn{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-slate-700 to-slate-900">
              €10k/Month
            </span>
            <br />
            by Dropshipping
          </h1>
          
          <p className="text-xl text-slate-600 mb-12 max-w-3xl mx-auto leading-relaxed animate-slide-up-delay">
            Master the complete dropshipping system that has helped thousands build 
            profitable online businesses. Learn proven strategies, avoid costly mistakes, 
            and start earning consistent income from day one.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
            <Button 
              onClick={scrollToPricing}
              size="lg"
              className="bg-slate-900 hover:bg-slate-800 text-white px-8 py-4 text-lg transition-all duration-300 transform hover:scale-105 shadow-lg hover:shadow-xl"
            >
              Start Your Journey - Only €15
            </Button>
            <Button 
              variant="outline"
              size="lg"
              onClick={() => document.getElementById("course").scrollIntoView({ behavior: "smooth" })}
              className="border-slate-300 text-slate-700 hover:bg-slate-50 px-8 py-4 text-lg transition-all duration-300"
            >
              Learn More
            </Button>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            <div className="text-center p-6 bg-white rounded-xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow duration-300">
              <div className="inline-flex items-center justify-center w-12 h-12 bg-slate-100 rounded-lg mb-4">
                <Users className="text-slate-600" size={24} />
              </div>
              <h3 className="text-2xl font-bold text-slate-900 mb-2">5,000+</h3>
              <p className="text-slate-600">Students Enrolled</p>
            </div>
            
            <div className="text-center p-6 bg-white rounded-xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow duration-300">
              <div className="inline-flex items-center justify-center w-12 h-12 bg-slate-100 rounded-lg mb-4">
                <DollarSign className="text-slate-600" size={24} />
              </div>
              <h3 className="text-2xl font-bold text-slate-900 mb-2">€2M+</h3>
              <p className="text-slate-600">Generated by Students</p>
            </div>
            
            <div className="text-center p-6 bg-white rounded-xl shadow-sm border border-slate-100 hover:shadow-md transition-shadow duration-300">
              <div className="inline-flex items-center justify-center w-12 h-12 bg-slate-100 rounded-lg mb-4">
                <TrendingUp className="text-slate-600" size={24} />
              </div>
              <h3 className="text-2xl font-bold text-slate-900 mb-2">95%</h3>
              <p className="text-slate-600">Success Rate</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;